- name: Install and Build Next.js Shopping Cart App
  hosts: localhost
  become: true

  vars:
    project_dir: /var/lib/jenkins/workspace/shopping-chart

  tasks:

    # Install base tools
    - name: Install dependencies required for setup
      apt:
        name:
          - curl
          - jq
          - build-essential
        state: present
        update_cache: yes

    # Read Node.js version from package.json
    - name: Read Node.js version from package.json
      shell: "jq -r '.engines.node' package.json"
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash
      register: node_version_raw

    # Extract major version (e.g., 18 from '>=18.16.0')
    - name: Extract major Node.js version
      set_fact:
        node_version: "{{ node_version_raw.stdout | regex_search('[0-9]+') }}"

    - name: Show detected Node.js version
      debug:
        msg: "Installing Node.js version {{ node_version }}"

    # Install Node.js using NodeSource
    - name: Install Node.js
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }}.x | bash -
        apt-get install -y nodejs
      args:
        executable: /bin/bash

    # Install PNPM globally
    - name: Install PNPM globally
      shell: npm install -g pnpm
      args:
        executable: /bin/bash

    # Install PM2 globally
    - name: Install PM2 globally
      shell: npm install -g pm2
      args:
        executable: /bin/bash

    # Clean old build artifacts
    - name: Remove old .next folder
      file:
        path: "{{ project_dir }}/.next"
        state: absent

    - name: Remove old node_modules
      file:
        path: "{{ project_dir }}/node_modules"
        state: absent

    - name: Remove old pnpm lock file
      file:
        path: "{{ project_dir }}/pnpm-lock.yaml"
        state: absent

    # Ensure clean permissions
    - name: Ensure node_modules directory exists
      file:
        path: "{{ project_dir }}/node_modules"
        state: directory
        owner: jenkins
        group: devops
        mode: '0775'
        recurse: yes

    # Install project dependencies using local pnpm
    - name: Install dependencies with PNPM
      shell: pnpm install
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash

    # Build Next.js project (with OpenSSL fix)
    - name: Build the Next.js project
      shell: pnpm exec next build
      environment:
        NODE_OPTIONS: "--openssl-legacy-provider"
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash

    # (Optional) Check installed Next.js version
    - name: Show Next.js version used
      shell: pnpm exec next --version
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash
      register: next_version

    - name: Print detected Next.js version
      debug:
        msg: "Next.js version used: {{ next_version.stdout }}"

    # Start the app using PM2
    - name: Start Next.js app using PM2
      shell: |
        pm2 delete shopping-cart || true
        pm2 start pnpm --name shopping-cart -- start
        pm2 save
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash
