- name: Build and Run Next.js Shopping Cart using Docker Compose
  hosts: localhost
  become: true

  vars:
    project_dir: /var/lib/jenkins/workspace/shopping-chart
    compose_file: "{{ project_dir }}/docker-compose.yml"
    node_version: "16"

  tasks:

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Show selected Node.js version
      debug:
        msg: "Using Node.js version: {{ node_version }}"

    # Template docker-compose.yml with hardcoded Node version
    - name: Generate docker-compose.yml
      copy:
        dest: "{{ compose_file }}"
        content: |
          version: '3.8'
          services:
            shopping-cart:
              image: node:{{ node_version }}-alpine
              container_name: shopping-cart
              working_dir: /app
              ports:
                - "3000:3000"
              volumes:
                - .:/app
              command: sh -c "
                npm install -g pnpm &&
                pnpm install &&
                pnpm build &&
                pnpm start
              "
              environment:
                NODE_ENV: production

    - name: Stop previous container
      shell: docker rm -f shopping-cart || true
      args:
        executable: /bin/bash

    - name: Run the app using Docker Compose
      shell: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash
