- name: Build and Run Shopping Cart App (single docker-compose call)
  hosts: localhost
  become: true

  vars:
    project_dir: /var/lib/jenkins/workspace/shopping-chart

  tasks:

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present
        update_cache: yes

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Clean up existing containers and volumes
      shell: docker-compose down -v || true
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash

    - name: Run all containers (pnpm install, deps, build, start) in one call
      shell: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash
