---
- name: Install and Build Next.js Shopping Cart App
  hosts: localhost
  become: false

  vars:
    project_dir: /var/lib/jenkins/workspace/shopping-chart

  tasks:
    - name: Install dependencies with PNPM
      ansible.builtin.shell: pnpm install
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash

    - name: Build the project (optional)
      ansible.builtin.shell: pnpm build || echo "No build step needed"
      args:
        chdir: "{{ project_dir }}"
        executable: /bin/bash
