---
- name: Build Next.js App with PNPM
  hosts: localhost
  become: false
  tasks:
    - name: Change to project directory
      ansible.builtin.command:
        cmd: pnpm install && pnpm build
      args:
        chdir: /var/lib/jenkins/workspace/shopping-chart
