version: '3.8'

services:
  install-pnpm:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["npm", "install", "-g", "pnpm"]

  install-deps:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["pnpm", "install"]
    depends_on:
      - install-pnpm

  build-app:
    image: node:16-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: ["pnpm", "build"]
    depends_on:
      - install-deps

  start-app:
    image: node:16-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["pnpm", "start"]
    depends_on:
      - build-app
    environment:
      NODE_ENV: production
