version: '3.8'

services:
  shopping-cart:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NODE_OPTIONS: --openssl-legacy-provider
    command:
      - /bin/sh
      - -c
      - |
        npm install -g pnpm &&
        pnpm install &&
        pnpm build &&
        pnpm start
