---
- name: Install and configure Nginx for Next.js app
  hosts: localhost
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Remove default Nginx config
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create Nginx config for Next.js app
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/shopping-cart
        content: |
          server {
              listen 80;
              server_name localhost;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Enable Nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/shopping-cart
        dest: /etc/nginx/sites-enabled/shopping-cart
        state: link
        force: true

    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
